# Writes the git revision stamp source (script mode: cmake -D... -P). Run by
# the frehg_git_revision target on every build, and once at configure time
# (FrehgGitRevision.cmake).
#
# Inputs:
#   FREHG_GIT_EXECUTABLE       git executable (empty or *-NOTFOUND: no git)
#   FREHG_GIT_SOURCE_DIR       source tree to stamp
#   FREHG_GIT_REVISION_OUTPUT  generated C++ source defining frehg::gitRevision()
#
# The stamp is "<sha12>" (git rev-parse --short=12 HEAD), "<sha12>-dirty" when
# a tracked file differs from HEAD, staged or not (untracked files do not
# count), or "unknown" when there is no git, HEAD has no commit, or the tree
# has no .git of its own (a release tarball, even one unpacked inside another
# checkout). The output is rewritten only when its content changes, so an
# unchanged stamp leaves the file's timestamp, and every object built from it,
# alone.

if(NOT CMAKE_SCRIPT_MODE_FILE)
  message(FATAL_ERROR "FrehgGitRevisionStamp.cmake runs in script mode (cmake -P)")
endif()
foreach(_var FREHG_GIT_SOURCE_DIR FREHG_GIT_REVISION_OUTPUT)
  if("${${_var}}" STREQUAL "")
    message(FATAL_ERROR "FrehgGitRevisionStamp.cmake: -D${_var}=... is required")
  endif()
endforeach()

# Stamp this tree only: drop any repository redirection inherited from the
# caller (a build launched from a git hook exports GIT_DIR). Take no optional
# locks: builds run beside the developer's own git commands, and a status
# that refreshed the index would contend for index.lock with them.
foreach(_var GIT_DIR GIT_WORK_TREE GIT_INDEX_FILE GIT_COMMON_DIR GIT_OBJECT_DIRECTORY)
  unset(ENV{${_var}})
endforeach()
set(ENV{GIT_OPTIONAL_LOCKS} 0)

set(_revision "unknown")
if(FREHG_GIT_EXECUTABLE AND EXISTS "${FREHG_GIT_SOURCE_DIR}/.git")
  execute_process(
    COMMAND "${FREHG_GIT_EXECUTABLE}" rev-parse --short=12 HEAD
    WORKING_DIRECTORY "${FREHG_GIT_SOURCE_DIR}"
    RESULT_VARIABLE _rc
    OUTPUT_VARIABLE _sha
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET)
  # The stamp lands in a C++ string literal: accept hex digits only.
  if(_rc EQUAL 0 AND _sha MATCHES "^[0-9a-f]+$")
    set(_revision "${_sha}")
    # A status that fails leaves the tree's state unproven; stamp it dirty
    # rather than claim a clean tree.
    execute_process(
      COMMAND "${FREHG_GIT_EXECUTABLE}" status --porcelain --untracked-files=no
      WORKING_DIRECTORY "${FREHG_GIT_SOURCE_DIR}"
      RESULT_VARIABLE _rc
      OUTPUT_VARIABLE _changes
      ERROR_QUIET)
    if(NOT _rc EQUAL 0 OR NOT _changes STREQUAL "")
      string(APPEND _revision "-dirty")
    endif()
  endif()
endif()

string(CONCAT _content
  "// Generated by cmake/FrehgGitRevisionStamp.cmake; do not edit.\n"
  "#include \"core/GitRevision.hpp\"\n"
  "\n"
  "namespace frehg {\n"
  "\n"
  "const char* gitRevision() noexcept { return \"${_revision}\"; }\n"
  "\n"
  "}  // namespace frehg\n")

set(_current "")
if(EXISTS "${FREHG_GIT_REVISION_OUTPUT}")
  file(READ "${FREHG_GIT_REVISION_OUTPUT}" _current)
endif()
if(NOT _current STREQUAL _content)
  # Write-then-rename: a reader never sees a half-written file.
  file(WRITE "${FREHG_GIT_REVISION_OUTPUT}.tmp" "${_content}")
  file(RENAME "${FREHG_GIT_REVISION_OUTPUT}.tmp" "${FREHG_GIT_REVISION_OUTPUT}")
  message(STATUS "Frehg2: git revision ${_revision}")
endif()
