# unit.git_revision_stamp: the output-file revision stamp tracks the source
# tree at build time (v2 plan V2-A20 finding 5).
#
# The run record's provenance.git_sha, the HDF5 /frehg2 git_sha attribute and
# the log header name the revision of the code that produced an output
# (frehg::gitRevision(), generated by cmake/FrehgGitRevision.cmake). A stamp
# captured at configure time survives every incremental rebuild (a commit or
# an edit touches no CMake input) and carries no dirty-tree marker, so a
# binary built from an edited tree names a commit that lacks the edit.
#
# This test configures a throwaway project that includes the real
# cmake/FrehgGitRevision.cmake (same target, same generator script, same CMake
# generator as the frehg build) on top of a throwaway git repository, plus a
# consumer that reads the generated source the way the compiler does: a
# DEPENDS-driven step ordered after the stamp target, as frehg_core is.
# Build by build:
#   clean      fresh commit              -> "<sha12>", no suffix
#   no-op      rebuild, nothing edited   -> source not rewritten, consumer not re-run
#   dirty      tracked file edited       -> "<sha12>-dirty", read by the consumer in the same build
#   no-op      rebuild, still dirty      -> not rewritten
#   commit     the edit committed        -> the new "<sha12>", no suffix
#   staged     edit staged, uncommitted  -> "<sha12>-dirty"
#   untracked  only an untracked file    -> no suffix
#   no git     git not found             -> "unknown"
#   tarball    source tree without .git inside another checkout -> "unknown"
# Needs git but no compiler; skipped (loudly) when git was not found.
#
# Inputs (-D): FREHG_CMAKE_MODULE_DIR, GIT_EXECUTABLE, WORK_DIR (must end in
# "git_revision_stamp"; it is wiped), TEST_GENERATOR, TEST_MAKE_PROGRAM
# (optional).

cmake_minimum_required(VERSION 3.23)

foreach(_var FREHG_CMAKE_MODULE_DIR WORK_DIR TEST_GENERATOR)
  if("${${_var}}" STREQUAL "")
    message(FATAL_ERROR "test_git_revision.cmake: -D${_var}=... is required")
  endif()
endforeach()
get_filename_component(_leaf "${WORK_DIR}" NAME)
if(NOT IS_ABSOLUTE "${WORK_DIR}" OR NOT _leaf STREQUAL "git_revision_stamp")
  message(FATAL_ERROR "test_git_revision.cmake: refusing to wipe WORK_DIR='${WORK_DIR}'")
endif()
if(NOT GIT_EXECUTABLE OR NOT EXISTS "${GIT_EXECUTABLE}")
  message("git_revision_stamp: SKIPPED, git not found (GIT_EXECUTABLE='${GIT_EXECUTABLE}')")
  return()
endif()

# Every git process below (the test's own, and the generator's, which inherits
# this environment through the nested builds) must see only the throwaway
# repository and a pristine configuration: no repository redirection or
# injected config from a caller (a git hook, a `git -c` wrapper), no global or
# system config (signing, hooks, fsmonitor), a fixed identity for commits.
foreach(_var GIT_DIR GIT_WORK_TREE GIT_INDEX_FILE GIT_COMMON_DIR
             GIT_OBJECT_DIRECTORY GIT_ALTERNATE_OBJECT_DIRECTORIES
             GIT_CEILING_DIRECTORIES GIT_TEMPLATE_DIR GIT_CONFIG
             GIT_CONFIG_GLOBAL GIT_CONFIG_SYSTEM GIT_CONFIG_PARAMETERS
             GIT_CONFIG_COUNT)
  unset(ENV{${_var}})
endforeach()
file(REMOVE_RECURSE "${WORK_DIR}")
file(MAKE_DIRECTORY "${WORK_DIR}/home")
set(ENV{HOME} "${WORK_DIR}/home")
set(ENV{XDG_CONFIG_HOME} "${WORK_DIR}/home")
set(ENV{GIT_CONFIG_NOSYSTEM} 1)
set(ENV{GIT_AUTHOR_NAME} "frehg2 test")
set(ENV{GIT_AUTHOR_EMAIL} "test@frehg2.invalid")
set(ENV{GIT_COMMITTER_NAME} "frehg2 test")
set(ENV{GIT_COMMITTER_EMAIL} "test@frehg2.invalid")

set(_repo "${WORK_DIR}/repo")
set(_bin "${WORK_DIR}/build")
file(MAKE_DIRECTORY "${_repo}")

set(_generator_args -G "${TEST_GENERATOR}")
if(NOT "${TEST_MAKE_PROGRAM}" STREQUAL "")
  list(APPEND _generator_args "-DCMAKE_MAKE_PROGRAM=${TEST_MAKE_PROGRAM}")
endif()

# Run a command in `dir`; a nonzero exit fails the test outright. Leaves its
# standard output in _run_output.
function(_run label dir)
  execute_process(COMMAND ${ARGN}
    WORKING_DIRECTORY "${dir}"
    RESULT_VARIABLE _rc
    OUTPUT_VARIABLE _out
    ERROR_VARIABLE _err
    OUTPUT_STRIP_TRAILING_WHITESPACE)
  if(NOT _rc EQUAL 0)
    string(REPLACE ";" " " _cmd "${ARGN}")
    message(FATAL_ERROR "[${label}] `${_cmd}` failed (${_rc}):\n${_out}\n${_err}")
  endif()
  set(_run_output "${_out}" PARENT_SCOPE)
endfunction()

macro(_git label)
  _run("${label}" "${_repo}" "${GIT_EXECUTABLE}" ${ARGN})
endmacro()

function(_configure label src bin)
  _run("${label}" "${WORK_DIR}" "${CMAKE_COMMAND}" -S "${src}" -B "${bin}"
       ${_generator_args} ${ARGN})
endfunction()

function(_build label bin)
  _run("${label}" "${WORK_DIR}" "${CMAKE_COMMAND}" --build "${bin}")
endfunction()

# The revision literal in a generated (or consumed) source.
function(_stamp_in file out)
  file(READ "${file}" _src)
  if(NOT _src MATCHES "return \"([^\"]*)\";")
    message(FATAL_ERROR "no revision literal in ${file}:\n${_src}")
  endif()
  set(${out} "${CMAKE_MATCH_1}" PARENT_SCOPE)
endfunction()

# Failed expectations accumulate; the test reports every one before failing.
set(_failures "")
macro(_fail msg)
  list(APPEND _failures "${msg}")
  message(STATUS "FAIL: ${msg}")
endmacro()

# The stamp the last build left in ${_generated} must equal `expected`. With
# CONSUMER, the consumer must have read that same stamp in the same build (it
# lags one build behind if the stamp is refreshed after the compile step
# rather than before it).
macro(_expect_stamp label expected)
  _stamp_in("${_generated}" _got)
  message(STATUS "[${label}] stamp '${_got}' (expected '${expected}')")
  if(NOT _got STREQUAL "${expected}")
    _fail("[${label}] stamp is '${_got}', expected '${expected}'")
  endif()
  if("${ARGN}" STREQUAL "CONSUMER")
    _stamp_in("${_bin}/consumer.cpp" _seen)
    if(NOT _seen STREQUAL _got)
      _fail("[${label}] the consumer read '${_seen}' in the same build; the stamp is '${_got}'")
    endif()
  endif()
endmacro()

# A no-op build must leave the generated source untouched (its timestamp is
# what decides recompilation) and must not re-run the consumer. The 1.1 s wait
# makes a rewrite visible even on a filesystem with 1 s timestamps.
macro(_expect_untouched label)
  file(TIMESTAMP "${_generated}" _gen_before "%s.%f" UTC)
  file(TIMESTAMP "${_bin}/consumer.cpp" _con_before "%s.%f" UTC)
  execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 1.1)
  _build("${label}" "${_bin}")
  file(TIMESTAMP "${_generated}" _gen_after "%s.%f" UTC)
  file(TIMESTAMP "${_bin}/consumer.cpp" _con_after "%s.%f" UTC)
  message(STATUS "[${label}] generated source ${_gen_before} -> ${_gen_after}")
  if(NOT _gen_before STREQUAL _gen_after)
    _fail("[${label}] the no-op build rewrote the generated source (${_gen_before} -> ${_gen_after})")
  endif()
  if(NOT _con_before STREQUAL _con_after)
    _fail("[${label}] the no-op build re-ran the consumer (${_con_before} -> ${_con_after})")
  endif()
endmacro()

# Sensitivity: the no-op checks compare timestamps across a build, so prove
# first that this filesystem exposes a same-content rewrite made after the
# same wait. Otherwise those checks could never fail.
file(WRITE "${WORK_DIR}/probe" "x")
file(TIMESTAMP "${WORK_DIR}/probe" _t0 "%s.%f" UTC)
execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 1.1)
file(WRITE "${WORK_DIR}/probe" "x")
file(TIMESTAMP "${WORK_DIR}/probe" _t1 "%s.%f" UTC)
if(_t0 STREQUAL _t1)
  message(FATAL_ERROR "sensitivity: a same-content rewrite 1.1 s later left the "
                      "timestamp at ${_t0}; the no-op checks would be vacuous here")
endif()

# The throwaway repository. Before any command that writes to it, confirm git
# resolves the directory to itself, never to an enclosing checkout.
_run(init "${_repo}" "${GIT_EXECUTABLE}" init -q)
_git(init rev-parse --show-toplevel)
file(REAL_PATH "${_repo}" _repo_real)
file(REAL_PATH "${_run_output}" _top_real)
if(NOT _top_real STREQUAL _repo_real)
  message(FATAL_ERROR "refusing to continue: git resolves ${_repo} to the "
                      "checkout at '${_run_output}', not the throwaway repository")
endif()

set(_project [=[
cmake_minimum_required(VERSION 3.23)
project(git_revision_stamp_probe LANGUAGES NONE)
list(APPEND CMAKE_MODULE_PATH "@FREHG_CMAKE_MODULE_DIR@")
include(FrehgGitRevision)
add_custom_command(OUTPUT "${CMAKE_BINARY_DIR}/consumer.cpp"
  COMMAND "${CMAKE_COMMAND}" -E copy "${FREHG_GIT_REVISION_SOURCE}"
          "${CMAKE_BINARY_DIR}/consumer.cpp"
  DEPENDS "${FREHG_GIT_REVISION_SOURCE}"
  VERBATIM)
add_custom_target(consumer ALL DEPENDS "${CMAKE_BINARY_DIR}/consumer.cpp")
add_dependencies(consumer frehg_git_revision)
file(WRITE "${CMAKE_BINARY_DIR}/generated-source.txt" "${FREHG_GIT_REVISION_SOURCE}")
]=])
string(CONFIGURE "${_project}" _project @ONLY)

file(WRITE "${_repo}/CMakeLists.txt" "${_project}")
file(WRITE "${_repo}/tracked.txt" "first\n")
_git(clean add CMakeLists.txt tracked.txt)
_git(clean commit -q -m first)
_git(clean rev-parse --short=12 HEAD)
set(_sha1 "${_run_output}")

_configure(clean "${_repo}" "${_bin}" "-DGIT_EXECUTABLE=${GIT_EXECUTABLE}")
file(READ "${_bin}/generated-source.txt" _generated)
_build(clean "${_bin}")
_expect_stamp(clean "${_sha1}" CONSUMER)

_expect_untouched(no-op)

file(APPEND "${_repo}/tracked.txt" "edited\n")
_build(dirty "${_bin}")
_expect_stamp(dirty "${_sha1}-dirty" CONSUMER)

_expect_untouched(no-op-dirty)

_git(commit commit -q -a -m second)
_git(commit rev-parse --short=12 HEAD)
set(_sha2 "${_run_output}")
_build(commit "${_bin}")
_expect_stamp(commit "${_sha2}" CONSUMER)

file(APPEND "${_repo}/tracked.txt" "staged\n")
_git(staged add tracked.txt)
_build(staged "${_bin}")
_expect_stamp(staged "${_sha2}-dirty")

_git(untracked commit -q -m third)
_git(untracked rev-parse --short=12 HEAD)
set(_sha3 "${_run_output}")
file(WRITE "${_repo}/untracked.txt" "not in git\n")
_build(untracked "${_bin}")
_expect_stamp(untracked "${_sha3}")

# No git at all: the same tree, configured with the Git package disabled.
_configure(no-git "${_repo}" "${WORK_DIR}/build-no-git" -DCMAKE_DISABLE_FIND_PACKAGE_Git=TRUE)
_build(no-git "${WORK_DIR}/build-no-git")
file(READ "${WORK_DIR}/build-no-git/generated-source.txt" _generated)
_expect_stamp(no-git "unknown")

# A tree without its own .git nested inside a checkout (a release tarball
# unpacked into a git-managed directory) must not stamp the enclosing
# checkout's revision. The nested tree is untracked, so the enclosing
# repository stays clean. Confirm git itself does resolve the enclosing
# checkout from there; otherwise this check proves nothing.
file(WRITE "${_repo}/tarball/CMakeLists.txt" "${_project}")
_run(tarball "${_repo}/tarball" "${GIT_EXECUTABLE}" rev-parse --show-toplevel)
file(REAL_PATH "${_run_output}" _top_real)
if(NOT _top_real STREQUAL _repo_real)
  message(FATAL_ERROR "sensitivity: git does not resolve ${_repo}/tarball to the "
                      "enclosing throwaway repository ('${_run_output}')")
endif()
_configure(tarball "${_repo}/tarball" "${WORK_DIR}/build-tarball"
           "-DGIT_EXECUTABLE=${GIT_EXECUTABLE}")
_build(tarball "${WORK_DIR}/build-tarball")
file(READ "${WORK_DIR}/build-tarball/generated-source.txt" _generated)
_expect_stamp(tarball "unknown")

if(_failures)
  list(LENGTH _failures _count)
  string(REPLACE ";" "\n  " _list "${_failures}")
  message(FATAL_ERROR "git_revision_stamp: ${_count} expectation(s) failed:\n  ${_list}")
endif()
message(STATUS "git_revision_stamp: every expectation holds")
